export enum ActionTypes {
	APP__CHANGE_OPEN_LOST_CONNECT_ALERT = 0x00,
    APP__SAVE_USER_DATA_IN_COOKIES = 0x01,
    APP__FIND_USER_DATA_IN_COOKIES = 0x02,
    APP__LOGOUT_AND_DELETE_COOKIES = 0x03,
}