export enum ActionTypes {
	APP__CHANGE_OPEN_LOST_CONNECT_ALERT = 0x00,
    APP__SAVE_USER_DATA_IN_COOKIES = 0x01,
    APP__FIND_USER_DATA_IN_COOKIES = 0x02,
    APP__LOGOUT_AND_DELETE_COOKIES = 0x03,
    APP__SAVE_URL_AFTER_RELOAD = 0x04,

    CREATE_POST__CHANGE_OPEN_STATE = 0x10,
    CREATE_POST__CREATE_NEW_POST = 0x11,
    CREATE_POST__CHANGE_IS_NEW_POST_UP = 0x12,

    MASTER_DIALOG__CHANGE_OPEN_STATE = 0x20,
    MASTER_DIALOG__SET_DIALOG_CONTENT = 0x21,

    UPDATE_POST__CHANGE_OPEN_STATE = 0x30,
    UPDATE_POST__SET_DATA = 0x31,
}